GET http://localhost:3000

### Create a new asset
POST http://localhost:3000/assets
Content-Type: application/json

{
    "id": "test",
    "symbol": "test",
    "price": 100
}

GET  http://localhost:3000/assets

GET  http://localhost:3000/wallets